apiVersion: v1
#create configMap = create namespace
kind: ConfigMap
matadata:
  name: mongo-config-map
  # config namespace
  # namespace: mongo-namespace
data:
  #key -value (database url and server name is name service chá»©a db)
  database_url: mongo-service
